baseURL = 'https://wheelsnipecelly.info/'
languageCode = 'en-us'
title = 'Wheel Snipe Celly'
theme = 'blog-theme'

[params]
    slogan = 'Breaking the ice, Analyzing the beauty of the game'

[data]
    enable = true

[permalinks]
    topics = "/:slug/"